export const url = 'http://localhost:5000'
export const BINANCE_SOCKET_API = 'fstream.binance.com'
export const BINANCE_TEST_SOCKET_API = 'fstream.binancefuture.com'
export const BINANCE_API = 'fapi.binance.com'
export const BINANCE_TEST_API = 'testnet.binancefuture.com'